# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180312_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='text', max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.CharField(default='teacher', max_length=20),
        ),
    ]
