# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 16:07
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180406_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='context',
            field=tinymce.models.HTMLField(default='HTML'),
        ),
    ]
