# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 19:35
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_section_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='section',
            name='text',
        ),
        migrations.AddField(
            model_name='course',
            name='context',
            field=tinymce.models.HTMLField(default='text'),
        ),
        migrations.AlterField(
            model_name='section',
            name='context',
            field=tinymce.models.HTMLField(),
        ),
    ]
