# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180409_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.URLField(default='link'),
        ),
    ]
