# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='link',
        ),
        migrations.AddField(
            model_name='section',
            name='link',
            field=models.URLField(default='link'),
        ),
    ]
