# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_useranswer_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='time',
            new_name='test_was_taken',
        ),
    ]
