# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20180515_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_comment',
            field=models.CharField(default='comment', max_length=600),
        ),
    ]
