# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_student_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student_comment',
            field=models.TextField(blank=True, default='comment', max_length=600),
        ),
    ]
